#!/bin/bash

# Update HOST with actual value, uniquely generated by Docker on each start
sed -i -E "s/HOST = [^)]+/HOST = $HOSTNAME/g" $ORACLE_HOME/network/admin/listener.ora
sed -i -E "s/HOST = [^)]+/HOST = $HOSTNAME/g" $ORACLE_HOME/network/admin/tnsnames.ora

# Default value baked into the image - bit kludgy this
SYS_SCRIPT_PASSWORD=P3hy3h6cl4O4IPnLZybQ

while true; do
    pmon=`ps -ef | grep pmon_$ORACLE_SID | grep -v grep`

    if [ "$pmon" == "" ]
    then
        date
        /etc/init.d/oracle-xe start
	sleep 1m

	if [ -n "$ORACLE_SYS_PASSWORD" ]; then
		for user in sys system; do
			echo alter user $user identified by \"$ORACLE_SYS_PASSWORD\"\; | /bin/su - oracle -c "sqlplus -s / as sysdba"
		done
		echo @$ORACLE_HOME/apex/apxxepwd.sql \"$ORACLE_SYS_PASSWORD\"\; | /bin/su - oracle -c "sqlplus -s / as sysdba"

		# Update the ORACLE_PASSWORD value if we're changing it as we use it next section
		SYS_SCRIPT_PASSWORD=$ORACLE_SYS_PASSWORD
	fi

	if [ -n "$STARTUP_SQL" ]; then
		echo @$STARTUP_SQL \"$ORACLE_USER\" \"$ORACLE_PASSWORD\"\; | /bin/su - oracle -c "sqlplus system/$SYS_SCRIPT_PASSWORD"
	fi
    fi
    sleep 60m
done;
